const productsData = [
	{
		key: 1,
		title: "Men Regular Fit Solid Spread Collar Casual Shirt",
		img: "https://rukminim1.flixcart.com/image/880/1056/xif0q/shirt/s/b/d/xl-st2-vebnor-original-imagc7pmjzvszphf-bb.jpeg?q=50",
		companyName: "VeBNoR",
		price: "1849",
		discountedPrice: "399",
		availableSizes: ["S", "M"],
	},
	{
		key: 2,
		title: "Men Regular Fit Solid Spread Collar Casual Shirt",
		img: "https://rukminim1.flixcart.com/image/880/1056/l16rde80/shirt/4/y/y/xxl-st2-vebnor-original-imagcsujaggmjyux.jpeg?q=50",
		companyName: "VeBNoR",
		price: "1849",
		discountedPrice: "429",
		availableSizes: ["L", "XL"],
	},
	{
		key: 3,
		title: "Printed Men Black, Red Track Pants",
		img: "https://rukminim1.flixcart.com/image/880/1056/kzblocw0/track-pant/y/9/u/l-tblrdjog-orgl-tripr-original-imagbcnrwyhh5j3v.jpeg?q=50",
		companyName: "TRIPR",
		price: "1999",
		discountedPrice: "264",
		availableSizes: ["XXL", "S"],
	},
	{
		key: 4,
		title: "Color Block Women Round Neck Maroon, Black T-Shirt",
		img: "https://rukminim1.flixcart.com/image/880/1056/l2arp8w0/shopsy-t-shirt/s/3/0/s-nmp-try-this-original-imag5xe3sdhgg8sg.jpeg?q=50",
		companyName: "GIRLS SHOPPIE",
		price: "999",
		discountedPrice: "249",
		availableSizes: ["XS", "S", "M"],
	},
	{
		key: 5,
		title: "Boyfriend Women Black Jeans",
		img: "https://rukminim1.flixcart.com/image/880/1056/xif0q/jean/y/6/n/32-jean-1439-blk-nifty-original-imagbf6htjfc4xnx-bb.jpeg?q=50",
		companyName: "Nifty",
		price: "1299",
		discountedPrice: "499",
		availableSizes: ["M", "L", "XL", "XXL"],
	},
	{
		key: 6,
		title: "Women Ethnic Dress Black Dress",
		img: "https://rukminim1.flixcart.com/image/880/1056/xif0q/kurta/y/g/9/xl-black-kurta-423a-metro-fashion-original-imafm7uha2n3wgzq-bb.jpeg?q=50",
		companyName: "METRO-FASHION",
		price: "2599",
		discountedPrice: "799",
		availableSizes: ["S", "M", "XL", "XXL"],
	},
];

export { productsData };
